import java.util.*;

class parkingLot{
    private String name;
    private List<Slot> slot = new ArrayList<>();
    
    public parkingLot(String name){
        this.name = name;
    }
    public String getName(){
        return name;
    }

    public void addSlot(Slot s){
        slot.add(s);
    }
     List<Slot> internalSlot(){
        return slot;
    }

    public List<Slot> getSlot(){
        return Collections.unmodifiableList(slot);
    }

}

class Vehicle{
    private String id;
    private String plate;

    public Vehicle(String id, String plate){
        this.id = id;
        this.plate = plate;

    }

    public String getId(){
        return id;
    }
    public String getPlate(){
        return plate;
    }

}

 class Slot{
    private String id;
    private slotStatus status = slotStatus.AVAILABLE;

    public Slot(String id){
        this.id = id;
    }

    public String getId(){
        return id;
    }

    public slotStatus getStatus(){
        return status;
    }

    void occupy(){
        this.status = slotStatus.OCCUPIED;
    }

    void free(){
        this.status = slotStatus.AVAILABLE;
    }
 }

 enum slotStatus{
    AVAILABLE,
    OCCUPIED
 }

 class Ticket{
    private String id;
    private Slot slot;
    private Vehicle vehicle;

    public Ticket(String id, Slot slot, Vehicle vehicle){
        this.id = id;
        this.slot = slot;
        this.vehicle = vehicle;
    }

    public String getId(){
        return id;
    }

    public Slot getSlot(){
        return slot;
    }

    public Vehicle getVehicle(){
        return vehicle;
    }
 }

 interface AllocationStrategy{
    Slot select(List<Slot> slot);
 }

 class FirstAvailableStrategy implements AllocationStrategy{
    public Slot select(List<Slot> slot){
        for(Slot s : slot) if (s.getStatus() == slotStatus.AVAILABLE) return s;

        return null;
    }

 }

 class lotManager{
    private final parkingLot lot;
    private final AllocationStrategy strategy;
    private final Map<String, Ticket> activeTickets = new HashMap<>();

    public lotManager(parkingLot lot, AllocationStrategy strategy){
        this.lot = lot;
        this.strategy = strategy;
    }
    
    public Ticket park(Vehicle v){
        Slot slot = strategy.select(lot.internalSlot());
        if(slot == null) return null;

        slot.occupy();

        Ticket t = new Ticket(UUID.randomUUID().toString(),slot,v);

        activeTickets.put(t.getId(), t);

        return t;
    }

    public boolean unpark(String ticketId){
        Ticket t = activeTickets.remove(ticketId);
        if(t==null){
            return false;
        }
        t.getSlot().free();

        return true;
    }

 }


public class parking_lot{

    public static void main(String[] args){

    parkingLot p = new parkingLot("A");
    p.addSlot(new Slot("A1"));

    lotManager l = new lotManager(p, new FirstAvailableStrategy());         // lot initialized

    Vehicle v1 = new Vehicle("V1", "HR-01-AA-1111");

    Ticket t1 = l.park(v1);                                                // ticket generated by parking

    System.out.println("Issued tickets:");
    System.out.println("  t1: " + t1.getId() + " slot=" + t1.getSlot().getId()); 

    Vehicle v4 = new Vehicle("V4","HR-05-BB-3333");
    Ticket t4 = l.park(v4);
    System.out.println("t4 is " + (t4 == null ? "null (lot full)" : "issued"));     // parking when full

    boolean ok = l.unpark(t1.getId());
    System.out.println("Unpark t1 -> " + ok);
        
    t4 = l.park(v4);
    System.out.println("After freeing, t4 slot=" + (t4 != null ? t4.getSlot().getId() : "none"));  //parking after freeing

    }
}